//-------TASK 1
DROP TABLESPACE TS_MKA

CREATE TABLESPACE TS_MKA
    DATAFILE 'C:\app\Tablespaces\TS_mka_pdb.dbf'
    SIZE 7 m
    AUTOEXTEND ON NEXT 5M
    MAXSIZE 20M
    EXTENT MANAGEMENT LOCAL;
    
//-----TASK 2
DROP TABLESPACE TS_MKA_TEMP

CREATE TEMPORARY TABLESPACE  TS_MKA_TEMP
    TEMPFILE 'C:\app\Tablespaces\TS_mka_temp.dbf'
    SIZE 5 m
    AUTOEXTEND ON NEXT 3M
    MAXSIZE 30M
    EXTENT MANAGEMENT LOCAL;
    
//-----TASK 3
SELECT FILE_NAME, TABLESPACE_NAME, STATUS, MAXBYTES, USER_BYTES FROM DBA_DATA_FILES
UNION
SELECT FILE_NAME, TABLESPACE_NAME, STATUS, MAXBYTES, USER_BYTES FROM DBA_TEMP_FILES;

//-----TASK 4

CREATE ROLE RL_MKACORE
SELECT *FROM DBA_ROLES WHERE ROLE LIKE 'RL%';
//-----TASK 5

SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE = 'RL_MKACORE'

//-----TASK 6

CREATE PROFILE PF_MKACORE LIMIT
    PASSWORD_LIFE_TIME 180
    SESSION_PER_USER 3
    FAILED_LOGIN_ATTEMPTS 7
    PASSWORD_LOCK_TIME 1
    PASSWORD_REUSE_TIME 10
    PASSWORD_GRACE_TIME DEFAULT
    CONNECT_TIME 180
    IDLE_TIME 30

//-----TASK 7

SELECT *FROM DBA_PROFILES WHERE PROFILE = 'PF_MKACORE'
SELECT *FROM DBA_PROFILES WHERE PROFILE = 'DEFAULT'

//-----TASK 8

CREATE USER MKACORE IDENTIFIED BY 12345
    DEFAULT TABLESPACE TS_MKA QUOTA UNLIMITED ON TS_MKA
    TEMPORARY TABLESPACE TS_MKA_TEMP
    PROFILE PF_MKACORE
    ACCOUNT UNLOCK
    PASSWORD EXPIRE

//---GRANT RL_MKACORE TO MKACORE
//-----TASK 9

//-----TASK 10

//-----TASK 11

CREATE TABLESPACE MKA_DATA
    DATAFILE 'C:\app\Tablespaces\TS_mka_data.dbf'
    SIZE 10 m